### ISSUE TITLE
queue equality tests

### ISSUE THREAD

**Issue by EthanGriffee** [Buntry/swdev20_a1p2#8]
In the test_queue_equality test, q1 is created with object o1, however q2 is also created with object o1. Since the specs for the destructor says to delete every object in the queue, wouldn't deleting both of these queues be an issue since it tries to free o1 twice?

**Comment by Buntry** [comment]
Well caught, I will fix that momentarily.

**Comment by eccabay** [comment]
Your fix of this issue caused another -- now in the queue equality tests, you don't delete q2, which allows for a small memory leak. Deleting q1 removes o1, but the memory holding q2 still remains, even though o1 does not. You can fix this by changing 
`delete q1;` to `q2->dequeue(); delete q1; delete q2;` at line 111 and add `delete q2` at line 233 so that each queue deletes itself and all involved elements properly.

**Comment by Buntry** [comment]
I will fix this shortly. Thanks for the heads up.

**Comment by Buntry** [comment]
Should be fixed, close this issue to confirm it.

**Comment by eccabay** [comment]
Github won't let me close it, but it's perfect now, thank you!
